version: '3.9'

x-env-db-connections: &dbenvs
  MYSQL_ROOT_PASSWORD: "1234"
  MYSQL_DATABASE: online_shop
  MYSQL_USER: dev
  MYSQL_PASSWORD: "passwd"

services:
  app:
    build:
      context: .
      dockerfile: ./.containers/go/Dockerfile
    container_name: app
    tty: true
    volumes:
      - ./app:/go/src/app
      - gobin:/go/bin
    working_dir: /go/src/app
    ports:
    - "8080:8080"
    command: sh -c air

  db:
    image: mysql:latest
    container_name: online_shop_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment: *dbenvs
    volumes:
      - mysql:/var/lib/mysql
      - .dockerdev/mysql-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
    ports:
      - 3316:3306

  db_migrate:
    build:
      context: .
      dockerfile: ./.containers/db_migrate/Dockerfile
    environment:
      <<: *dbenvs
      # root ---
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      # --------
      MYSQL_HOST: online_shop_db
      MYSQL_PORT: 3306
    volumes:
      - ./db:/db
    working_dir: /db
    command: noop

volumes:
  mysql:
  gobin:
