BEGIN;

  CREATE TABLE IF NOT EXISTS products (
    -- COMMON SQL
    -- id          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id          INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name        CHARACTER VARYING(255) NOT NULL,
    price       INTEGER NOT NULL,
    description CHARACTER VARYING(255) NOT NULL,
    image       CHARACTER VARYING(255) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP NULL DEFAULT NULL
  );

COMMIT;
